version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/boat {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build boat -out=bin/boat
    aliases:
      - b
    silent: true
    sources:
      - './boat/**/*.odin'
    generates:
      - bin/boat

interval: 250ms
