version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/mirage {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build mirage -o:speed -out=bin/mirage
    aliases:
      - b
    silent: true
    sources:
      - './mirage/**/*.odin'
    generates:
      - bin/mirage

interval: 250ms
