version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/cosmic {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build cosmic -o:speed -out=bin/cosmic
    aliases:
      - b
    silent: true
    sources:
      - './cosmic/**/*.odin'
    generates:
      - bin/cosmic

interval: 250ms
