version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/pipe {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build pipe -o:speed -out=bin/pipe
    aliases:
      - b
    silent: true
    sources:
      - './pipe/**/*.odin'
    generates:
      - bin/pipe

interval: 250ms
