version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/cube {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build cube -out=bin/cube
    aliases:
      - b
    silent: true
    sources:
      - './cube/**/*.odin'
    generates:
      - bin/cube

interval: 250ms
