version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/floor {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build floor -out=bin/floor
    aliases:
      - b
    silent: true
    sources:
      - './floor/**/*.odin'
    generates:
      - bin/floor

interval: 250ms
